apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator-deployment: bitwarden-secretoperator
  name: bitwarden-secretoperator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      operator: bitwarden-secretoperator
  template:
    metadata:
      labels:
        operator: bitwarden-secretoperator
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # envFrom:
        # - configMapRef:
        #     name: webhook-config
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 1
        name: operator
        ports:
        - containerPort: 5000
          name: http
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      terminationGracePeriodSeconds: 10